//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPrice
    {
        public int ID { get; set; }
        public Nullable<int> RoutID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
