//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasStation
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Branch { get; set; }
        public string Province { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
    }
}
