//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Symptom { get; set; }
        public string MaintenanceTypeID { get; set; }
        public Nullable<int> TruckID { get; set; }
        public string Solution { get; set; }
        public string Detail { get; set; }
        public string Technician { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
