//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> OID { get; set; }
        public string OrderID { get; set; }
        public string ContainerNo { get; set; }
        public string Position { get; set; }
        public string PackNo { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
