//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int ID { get; set; }
        public string FromDetail { get; set; }
        public string FromProvince { get; set; }
        public string ToDetail { get; set; }
        public string ToProvince { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<decimal> OilVolume { get; set; }
        public Nullable<decimal> Toll { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<decimal> OTPrice { get; set; }
        public Nullable<decimal> OTPriceMonth { get; set; }
        public string OTDetail { get; set; }
        public Nullable<decimal> POTPrice { get; set; }
        public Nullable<decimal> POTPriceMonth { get; set; }
        public string POTDetail { get; set; }
        public Nullable<decimal> TaxPrice { get; set; }
        public Nullable<decimal> TaxPriceMonth { get; set; }
        public string TaxDetail { get; set; }
        public Nullable<decimal> HPrice { get; set; }
        public Nullable<decimal> HPriceMonth { get; set; }
        public string HDetail { get; set; }
        public Nullable<decimal> SPrice { get; set; }
        public Nullable<decimal> SPriceMonth { get; set; }
        public string SDetail { get; set; }
        public Nullable<decimal> PSPrice { get; set; }
        public Nullable<decimal> PSPriceMonth { get; set; }
        public string PSDetail { get; set; }
        public Nullable<decimal> STaxPrice { get; set; }
        public Nullable<decimal> STaxPriceMonth { get; set; }
        public string STaxDetail { get; set; }
        public Nullable<decimal> ITPrice { get; set; }
        public Nullable<decimal> ITPriceMonth { get; set; }
        public string ITDetail { get; set; }
        public Nullable<decimal> IHPrice { get; set; }
        public Nullable<decimal> IHPriceMonth { get; set; }
        public string IHDetail { get; set; }
        public Nullable<decimal> IPPrice { get; set; }
        public Nullable<decimal> IPPriceMonth { get; set; }
        public string IPDetail { get; set; }
        public Nullable<decimal> LTPrice { get; set; }
        public Nullable<decimal> LTPriceMonth { get; set; }
        public string LTDetail { get; set; }
        public Nullable<decimal> LHPrice { get; set; }
        public Nullable<decimal> LHPriceMonth { get; set; }
        public string LHDetail { get; set; }
        public Nullable<decimal> GPSPrice { get; set; }
        public Nullable<decimal> GPSPriceMonth { get; set; }
        public string GPSDetail { get; set; }
        public Nullable<decimal> SalaryPrice { get; set; }
        public Nullable<decimal> SalaryPriceMonth { get; set; }
        public string SalaryDetail { get; set; }
        public Nullable<decimal> OtherPrice { get; set; }
        public Nullable<decimal> OtherPriceMonth { get; set; }
        public string OtherDetail { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
        public Nullable<decimal> RentPriceMonth { get; set; }
        public string RentDetail { get; set; }
        public Nullable<decimal> MPrice { get; set; }
        public Nullable<decimal> MPriceMonth { get; set; }
        public string MDetail { get; set; }
        public Nullable<decimal> CPrice { get; set; }
        public Nullable<decimal> CPriceMonth { get; set; }
        public string CDetail { get; set; }
        public Nullable<decimal> SumPrice { get; set; }
        public Nullable<decimal> SumPriceMonth { get; set; }
        public string SumDetail { get; set; }
        public Nullable<decimal> CPPrice { get; set; }
        public Nullable<decimal> CPPriceMonth { get; set; }
        public string CPDetail { get; set; }
        public Nullable<decimal> OilPrice { get; set; }
        public Nullable<decimal> OilPriceMonth { get; set; }
        public string OilDetail { get; set; }
        public Nullable<decimal> TirePrice { get; set; }
        public Nullable<decimal> TirePriceMonth { get; set; }
        public string TireDetail { get; set; }
        public Nullable<decimal> DrivePrice { get; set; }
        public Nullable<decimal> DrivePriceMonth { get; set; }
        public string DriveDetail { get; set; }
        public Nullable<decimal> RPrice { get; set; }
        public Nullable<decimal> RPriceMonth { get; set; }
        public string RDetail { get; set; }
        public Nullable<decimal> VarPrice { get; set; }
        public Nullable<decimal> VarPriceMonth { get; set; }
        public string VarDetail { get; set; }
        public Nullable<int> NDay { get; set; }
        public Nullable<int> NPerDay { get; set; }
        public Nullable<int> NMonth { get; set; }
    }
}
