//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string SDetail { get; set; }
        public Nullable<decimal> SNumber { get; set; }
        public string SRemark { get; set; }
    }
}
