//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TireChange
    {
        public int ID { get; set; }
        public Nullable<decimal> Date { get; set; }
        public Nullable<int> TruckID { get; set; }
        public Nullable<double> Mile { get; set; }
        public Nullable<int> Position { get; set; }
        public string TakeOffSerial { get; set; }
        public string TakeOffBrand { get; set; }
        public string TakeOffSize { get; set; }
        public string PutOnSerial { get; set; }
        public string PutOnBrand { get; set; }
        public string PutOnSize { get; set; }
    }
}
