//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tire
    {
        public int ID { get; set; }
        public string SN { get; set; }
        public Nullable<decimal> SizeTire { get; set; }
        public Nullable<decimal> UsedKM { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> ExprieDate { get; set; }
        public string SaleBy { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> TruckID { get; set; }
        public Nullable<int> PositionWheel { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
