//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int ID { get; set; }
        public string JobID { get; set; }
        public Nullable<System.DateTime> OpenJobDate { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string TransferTime { get; set; }
        public Nullable<decimal> OOli { get; set; }
        public Nullable<decimal> OWay { get; set; }
        public Nullable<decimal> OOther { get; set; }
        public string ORemark { get; set; }
        public Nullable<System.DateTime> CloseJobDate { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string ArriveTime { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string ReturnTime { get; set; }
        public Nullable<decimal> ROli { get; set; }
        public Nullable<decimal> RDistance { get; set; }
        public Nullable<decimal> CMile { get; set; }
        public Nullable<decimal> COli { get; set; }
        public Nullable<decimal> CWay { get; set; }
        public Nullable<decimal> COther { get; set; }
        public string CRemark { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<decimal> DriverCost { get; set; }
        public Nullable<decimal> SIncome { get; set; }
        public Nullable<decimal> RIncome { get; set; }
        public Nullable<decimal> AllIncome { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> OMile { get; set; }
        public Nullable<decimal> WcarB { get; set; }
        public Nullable<decimal> WGas { get; set; }
        public Nullable<decimal> WcarW { get; set; }
    }
}
