//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public int ID { get; set; }
        public string License { get; set; }
        public string Brand { get; set; }
        public string TruckType { get; set; }
        public string Detail { get; set; }
        public string HitchLicense { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> weightTruck { get; set; }
        public Nullable<decimal> WeightSum { get; set; }
        public string BrandEngine { get; set; }
        public string NumberEngine { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> NumberPresure { get; set; }
        public Nullable<decimal> HosePower { get; set; }
        public Nullable<int> NumWheel { get; set; }
        public Nullable<decimal> SizeWheel { get; set; }
        public string TypeFuel { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string ChassisNumber { get; set; }
        public Nullable<decimal> RWeight { get; set; }
        public Nullable<System.DateTime> ExprieDate { get; set; }
        public Nullable<decimal> RTax { get; set; }
        public string ICompany { get; set; }
        public string INumber { get; set; }
        public Nullable<System.DateTime> IExprieDate { get; set; }
        public string IType { get; set; }
        public Nullable<decimal> IPremium { get; set; }
        public string IBroker { get; set; }
        public string IContact { get; set; }
        public string IMobile { get; set; }
        public string ACompany { get; set; }
        public string ANumber { get; set; }
        public Nullable<System.DateTime> AExprieDate { get; set; }
        public Nullable<decimal> APremium { get; set; }
        public Nullable<int> HitchID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
