//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CKLINE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        public int ID { get; set; }
        public string LicensePlate { get; set; }
        public string Brand { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public string TruckType { get; set; }
        public string Model { get; set; }
        public string EngineBrand { get; set; }
        public string Insurer { get; set; }
        public string InsuranceNum { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<int> HeadID { get; set; }
    }
}
